name: deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1 
      - uses: ./.github/actions/build-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}